# Конфигурация для spring + (в перспективе) postgresql

version: '3'
services:
  postgres:
    image: "postgres:latest"
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /home/dmitry/docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    #      - POSTGRES_USER=postgres
    network_mode: host

  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    restart: on-failure
    ports:
      - "8080:8080"
#    environment:

    network_mode: host