openapi: 3.0.4
info:
  title: Mortgageplace log models
  description: Log models for logging services of mortgageplace
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: { }

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        mg:
          $ref: '#/components/schemas/MgLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    MgLogModel:
      title: Модель лога для микросервиса mortgageplace
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - search
            - offers
        requestAd:
          $ref: '#/components/schemas/MgLog'
        requestFilter:
          $ref: '#/components/schemas/MgFilterLog'
        responseAds:
          type: array
          items:
            $ref: '#/components/schemas/MgLog'

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    MgLog:
      title: Модель лога для объявления
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        borrowerCategoryModel:
          type: string
        visibility:
          type: string
        rate:
          type: string
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string

    MgFilterLog:
      title: Модель лога фильтра
      properties:
        searchString:
          type: string
        bankId:
          type: string

